### ISSUE TITLE
Suggest to flush all caches

### ISSUE THREAD

**Issue by xperseguers** [waldhacker/ext-hcaptcha#4]
I installed the extension using composer. However I couldn't see the new hcaptcha element in the Form wizard until I went to Maintenance and flushed the whole cache.

**Comment by ProWebs** [comment]
Are you sure this was the only thing you have done? We don't used composer only the EM but we had the same issue and flushing all cache won't solve it.

**Comment by xperseguers** [comment]
@ProWebs This is old now but no, I didn't do other things. Beware that "flushing the whole cache" is not done with the thunder icon in the Backend's toolbar but really from within the Install Tool.

You are not using composer? You really should switch asap as composer is the very recommended way of installing TYPO3 nowadays.

**Comment by ProWebs** [comment]
I have done this from install tool, but this hasn't the effect that it works.

**Comment by waldhacker1** [comment]
@ProWebs 
I think your issue is this: #15.
This has now been fixed with version 2.1.1.
At the moment it is not possible to release into TER, but as soon as this is possible again, the version 2.1.1 can be used in non-composer TYPO3 installations too.

@xperseguers Thank you for your suggestion. I have included a note in the documentation.
